USE [master]
GO

/****** Object:  Database [AgroConnect]    Script Date: 9/2/2026 20:58:07 ******/
CREATE DATABASE [AgroConnect]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AgroConnect', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AgroConnect.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AgroConnect_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AgroConnect_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AgroConnect].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AgroConnect] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AgroConnect] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AgroConnect] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AgroConnect] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AgroConnect] SET ARITHABORT OFF 
GO

ALTER DATABASE [AgroConnect] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AgroConnect] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AgroConnect] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AgroConnect] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AgroConnect] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AgroConnect] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AgroConnect] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AgroConnect] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AgroConnect] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AgroConnect] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AgroConnect] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AgroConnect] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AgroConnect] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AgroConnect] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AgroConnect] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AgroConnect] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AgroConnect] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AgroConnect] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AgroConnect] SET  MULTI_USER 
GO

ALTER DATABASE [AgroConnect] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AgroConnect] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AgroConnect] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AgroConnect] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AgroConnect] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AgroConnect] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AgroConnect] SET  READ_WRITE 
GO

